name: gh-pages

on:
  push:
    branches:
      - master
      - main

jobs:
  build-and-deploy:
    name: Deploy to gh-pages
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Select NodeJS version
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 18

      - name: Install and Build
        run: |
          yarn install
          yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@94f3c658273cf92fb48ef99e5fbc02bd2dc642b2 # v4.6.3
        with:
          branch: gh-pages
          folder: public
