name: Publish

on:
  push:
    branches:
      - main

concurrency: publish

jobs:
  qa:
    name: 🔹 QA
    uses: oliversalzburg/workflows/.github/workflows/qa-browser-app.yml@main

  pre-release:
    if: github.ref_name == github.event.repository.default_branch
    name: 🔹 Publish
    needs: qa
    permissions:
      contents: read
      id-token: write
      packages: read
      pages: write
      pull-requests: read
    uses: oliversalzburg/workflows/.github/workflows/publish-browser-app.yml@main
    with:
      wants-github-release: false
